version: 2

sources:
  - name: gz_raw_data
    schema: raw
    tables:
      - name: raw_gz_sales
        identifier: sales
      - name: raw_gz_product
        identifier: product
      - name: raw_gz_ship
        identifier: ship
